[general]
n = 200
re = 1000
alpha = {r = 0.7, i = 0.0}
beta = {r = 0.0, i = 0.0}
omega = {r = 0.0, i = 0.0}

[flags]
branch = "temporal" # Options are: "temporal", "spatial"
problem = "Custom" # Options are: "BoundaryLayer, "Poiseuille", "Couette", "Custom"
fileWriteEigenvalues = "data/eigenvalues.dat"
doPlot = false
use_c = false # When temporal branch is used, plot in terms of c instead of omega (omega = alpha * c)
run_multiple = true

# fill only when problem = "Custom"
[customProblemFlags]
# filenameUprofile = "/home/victor/Desktop/PhD/src/flatSurfaceRe1000IncNS/dns/oldSetups/08_changedformula_newUpperBC/data/points_x660_n2800.dat"
filenameUprofile = "/home/victor/Desktop/PhD/src/boeingGapRe1000IncNS/baseflow/dns/d4_w15/data/points_x900_n400.dat"
plotUprofile = false
colX = 1
colY = 2
numSkipHeaderLines = 3

# fill only when run_multiple = true
[runMultipleFlags]
vars_r = {min = 0.05, max = 0.4, num = 50}
vars_i = {min = 0.0, max = 0.0, num = 1}

[plot]
plot_lims = {xmin = 0.0, xmax = 1.2, ymin = -2, ymax = 0.1}

